### ISSUE TITLE
Track context menu doesn't always close

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#247]
_Commit_: http://higlass.io

#### Steps to reproduce
1. Open and close many track config menus

#### Observed behavior
- Somehow elements of old context menus are not properly destroyed:

<img width="1434" alt="screen shot 2018-04-28 at 4 56 29 pm" src="https://user-images.githubusercontent.com/932103/39400807-5b28aa56-4b05-11e8-884f-3eed8e97ff9f.png">

```
Uncaught TypeError: e.props.onClick is not a function
    at t (hglib.js:1)
    at Object.r (react-dom.min.js:14)
    at a (react-dom.min.js:12)
    at Object.s [as executeDispatchesInOrder] (react-dom.min.js:12)
    at f (react-dom.min.js:12)
    at m (react-dom.min.js:12)
    at Array.forEach (<anonymous>)
    at r (react-dom.min.js:15)
    at Object.processEventQueue (react-dom.min.js:12)
    at r (react-dom.min.js:14)
9react-dom.min.js:15 Uncaught Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=%20Check%20the%20render%20method%20of%20%60t%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (react-dom.min.js:15)
    at i (react-dom.min.js:15)
    at Object.updateChildren (react-dom.min.js:13)
    at h._reconcilerUpdateChildren (react-dom.min.js:14)
    at h._updateChildren (react-dom.min.js:14)
    at h.updateChildren (react-dom.min.js:14)
    at h._updateDOMChildren (react-dom.min.js:13)
    at h.updateComponent (react-dom.min.js:13)
    at h.receiveComponent (react-dom.min.js:13)
    at Object.receiveComponent (react-dom.min.js:14)
```

#### Expected behavior
- Menus should always close

**Comment by pkerpedjiev** [comment]
Fixed by setting its position to `fixed'. Should work in `v1.0.0-alpha.8`.
